import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderHome from "./(pages)/component/HeaderHome";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// children tuong tu nhu Outlet cua React
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
          integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
          //  rename style Scamel Case
          // crossorigin="anonymous"
          crossOrigin="anonymous"
          // referrerpolicy="no-referrer"
          referrerPolicy="no-referrer"
        />
        <link rel="canonical" href="https://next-js-rho-gray.vercel.app/" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderHome />
        {children}
      </body>
    </html>
  );
}
